### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by ryanhoetger** [AnotherKamila/nook-revival#1]
I am actually unable to download this due to a detected virus.

**Comment by AnotherKamila** [comment]
The exploit used to root the Nook may be detected as a "virus", because it is used to gain unauthorised access to the device (in this case the Nook).

I expect that the file causing the virus detection alarm to go off is the `ratc.bin` file (and nothing else). If you want to use this, you'll need to add an exception to your antivirus software (and remove it when you're done, as you won't need to do it more than once).

Of course, I could be lying, and I have no way to prove that I'm not, other saying "I used this on my Nook, look at the photos in the README (which could be photoshopped) and I promise it doesn't do anything bad". Trust is a tricky thing :-)

One way to be able to trust this would be to check the details of the virus detection in your antivirus program. The RATC exploit is a well-known thing, so it is quite likely that your antivirus shows RATC (or something related) and not something completely different. If that is the case **and** if you independently verify online that the RATC exploit is used to get root on old Android devices rather than infect your PC, then you can be reasonably sure that this is in fact doing what I claim.

**Comment by AnotherKamila** [comment]
By the way, thank you for letting me know. I have not thought about documenting that. I added a link to this issue into the README.
